name: Web build and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - 'src/**/*'

jobs:
  web-release:
    name: Build & Deploy Web
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 17.7.0
          cache: 'npm'

      - run: npm ci
      - run: npm run build

      - uses: a7ul/tar-action@v1.1.0
        with:
          command: c
          files: |
            dist/
            captain-definition
            nginx.conf
            Dockerfile
          outPath: deploy.tar

      - name: Deploy App to CapRover
        uses: caprover/deploy-from-github@v1.0.1
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'
          app: '${{ secrets.APP_NAME }}'
          token: '${{ secrets.APP_TOKEN }}'
